"use client";

import { useState, useRef, useCallback } from "react";
import { Package, Plus, ChevronRight, DollarSign, TrendingUp, Share2, X, Download } from "lucide-react";
import { useApp } from "@/context/AppContext";

export default function InventoryPage() {
  const { ammo, rifles, shots, getShotCountForLot, getLotCost, getLotCostPerRound, getGrade, getSD, getES, getAvgGroup, getAvgVertical } = useApp();
  const [reportLotId, setReportLotId] = useState<string | null>(null);
  const reportRef = useRef<HTMLDivElement>(null);

  // Total investment
  const totalInvestment = ammo.reduce((sum, lot) => sum + getLotCost(lot), 0);
  const totalRounds = ammo.reduce((sum, lot) => sum + lot.quantityRemaining, 0);

  const reportLot = ammo.find((a) => a.id === reportLotId);

  const handleShare = useCallback(async () => {
    if (!reportRef.current) return;
    try {
      // Use html-to-canvas alternative: create a text-based share
      const lot = reportLot;
      if (!lot) return;
      const bestGrade = rifles.reduce((best, r) => {
        const g = getGrade(r.id, lot.id);
        return g.score > best.score ? { ...g, rifle: `${r.make} ${r.model}` } : best;
      }, { grade: "N/A", color: "#8E8E93", score: 0, rifle: "" });

      const text = [
        `🎯 LevelUP Lot Report`,
        `━━━━━━━━━━━━━━━━━━━`,
        `${lot.brand} ${lot.model} — Lot #${lot.lotNumber}`,
        ``,
        `Grade: ${bestGrade.grade} (${bestGrade.score}/100)`,
        `Best in: ${bestGrade.rifle}`,
        ``,
        `SD: ${getSD(lot.id)} fps`,
        `ES: ${getES(lot.id)} fps`,
        `Shots Logged: ${getShotCountForLot(lot.id)}`,
        ``,
        `Cost: $${getLotCostPerRound(lot).toFixed(3)}/rd`,
        `Investment: $${getLotCost(lot).toFixed(2)}`,
        `Remaining: ${lot.quantityRemaining} rounds`,
        ``,
        `Generated by LevelUP Precision Platform`,
      ].join("\n");

      if (navigator.share) {
        await navigator.share({
          title: `${lot.brand} ${lot.model} — Lot #${lot.lotNumber}`,
          text,
        });
      } else {
        await navigator.clipboard.writeText(text);
        alert("Report copied to clipboard!");
      }
    } catch (err) {
      console.error("Share failed:", err);
    }
  }, [reportLot, rifles, getGrade, getSD, getES, getShotCountForLot, getLotCostPerRound, getLotCost]);

  return (
    <main className="p-4 max-w-md mx-auto space-y-6 pt-8 pb-10">
      <header className="flex justify-between items-end mb-6">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">
            <span className="text-white font-extrabold">Level</span><span className="bg-gradient-to-r from-green-400 to-emerald-500 bg-clip-text text-transparent font-extrabold">UP</span>{" "}
            Inventory
          </h1>
          <p className="text-[11px] font-medium tracking-widest uppercase text-textSecondary/60 mt-0.5">
            Lot Evaluation & Velocity Error Logger
          </p>
          <p className="text-textSecondary text-sm mt-1">
            {ammo.length} lot{ammo.length !== 1 ? "s" : ""} tracked
          </p>
        </div>
        <button className="w-10 h-10 rounded-full bg-gradient-to-r from-green-400 to-emerald-500 flex items-center justify-center shadow-lg shadow-green-500/20 active:scale-95 transition-transform">
          <Plus className="w-5 h-5 text-black" />
        </button>
      </header>

      {/* Investment Summary */}
      <div className="grid grid-cols-2 gap-3">
        <div className="ios-card bg-gradient-to-br from-[#1C1C1E] to-[#0A0A0A]">
          <div className="flex items-center gap-2 mb-2">
            <DollarSign className="w-4 h-4 text-green-500" />
            <span className="text-xs text-textSecondary font-medium">Total Invested</span>
          </div>
          <p className="text-2xl font-bold tracking-tight">${totalInvestment.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
        </div>
        <div className="ios-card bg-gradient-to-br from-[#1C1C1E] to-[#0A0A0A]">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-primary" />
            <span className="text-xs text-textSecondary font-medium">Rounds on Hand</span>
          </div>
          <p className="text-2xl font-bold tracking-tight">{totalRounds.toLocaleString()}</p>
        </div>
      </div>

      {/* Lot Cards */}
      <div className="space-y-3">
        {ammo.map((lot) => {
          const shotsFired = getShotCountForLot(lot.id);
          const costPerRound = getLotCostPerRound(lot);
          const totalCost = getLotCost(lot);
          const grades = rifles.map((r) => ({ ...getGrade(r.id, lot.id), rifleId: r.id }));
          const bestGrade = grades.reduce((best, g) =>
            g.score > best.score ? g : best, grades[0]);
          const bestRifle = rifles.find((r) => r.id === bestGrade.rifleId);

          return (
            <div key={lot.id} className="ios-card space-y-3">
              <div className="flex justify-between items-start">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full bg-[#2C2C2E] flex items-center justify-center">
                    <Package className="w-5 h-5 text-textSecondary" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-base">
                      {lot.brand} {lot.model}
                    </h3>
                    <p className="text-xs text-textSecondary">
                      Lot #{lot.lotNumber} • {shotsFired} shots logged
                    </p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {bestGrade.grade !== "N/A" && (
                    <div
                      className="text-lg font-black w-9 h-9 rounded-lg flex items-center justify-center"
                      style={{
                        color: bestGrade.color,
                        backgroundColor: bestGrade.color + "15",
                      }}
                    >
                      {bestGrade.grade}
                    </div>
                  )}
                </div>
              </div>

              {/* Stats Row */}
              <div className="flex items-center justify-between bg-[#0A0A0A] rounded-xl px-3 py-2.5">
                <div className="text-center">
                  <p className="text-sm font-bold">{lot.quantityRemaining.toLocaleString()}</p>
                  <p className="text-[10px] text-textSecondary">rds left</p>
                </div>
                <div className="w-px h-6 bg-[#2C2C2E]" />
                <div className="text-center">
                  <p className="text-sm font-bold">${costPerRound.toFixed(2)}</p>
                  <p className="text-[10px] text-textSecondary">/round</p>
                </div>
                <div className="w-px h-6 bg-[#2C2C2E]" />
                <div className="text-center">
                  <p className="text-sm font-bold">${totalCost.toFixed(0)}</p>
                  <p className="text-[10px] text-textSecondary">invested</p>
                </div>
                <div className="w-px h-6 bg-[#2C2C2E]" />
                <div className="text-center">
                  <p className="text-sm font-bold text-primary">{bestRifle?.make || "—"}</p>
                  <p className="text-[10px] text-textSecondary">best in</p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-2">
                <button
                  onClick={() => setReportLotId(lot.id)}
                  className="flex-1 flex items-center justify-center gap-2 bg-[#2C2C2E] rounded-xl py-2.5 active:scale-95 transition-transform"
                >
                  <Share2 className="w-3.5 h-3.5 text-primary" />
                  <span className="text-xs font-semibold">Share Report</span>
                </button>
              </div>
            </div>
          );
        })}
      </div>

      {/* Lot Report Modal */}
      {reportLot && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
          <div className="w-full max-w-sm" ref={reportRef}>
            {/* Report Card */}
            <div className="bg-gradient-to-br from-[#1C1C1E] to-[#0A0A0A] rounded-2xl border border-[#2C2C2E] overflow-hidden shadow-2xl">
              {/* Header */}
              <div className="bg-gradient-to-r from-green-400 to-emerald-500 px-6 py-4">
                <div className="flex justify-between items-center">
                  <div>
                    <p className="text-black text-xs font-bold uppercase tracking-wider opacity-70">Level<span className="font-black">UP</span> Lot Report</p>
                    <h2 className="text-black text-xl font-black mt-1">
                      {reportLot.brand} {reportLot.model}
                    </h2>
                    <p className="text-black/70 text-sm font-medium">Lot #{reportLot.lotNumber}</p>
                  </div>
                  <div className="text-right">
                    {(() => {
                      const bestGrade = rifles.reduce((best, r) => {
                        const g = getGrade(r.id, reportLot.id);
                        return g.score > best.score ? { ...g, rifle: `${r.make} ${r.model}` } : best;
                      }, { grade: "N/A", color: "#8E8E93", score: 0, rifle: "" });
                      return (
                        <div className="bg-black/20 backdrop-blur-sm rounded-xl px-4 py-2 text-center">
                          <p className="text-3xl font-black text-white">{bestGrade.grade}</p>
                          <p className="text-white/70 text-[10px]">{bestGrade.score}/100</p>
                        </div>
                      );
                    })()}
                  </div>
                </div>
              </div>

              {/* Metrics Grid */}
              <div className="grid grid-cols-2 gap-px bg-[#2C2C2E]">
                <div className="bg-[#1C1C1E] px-4 py-3">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Std Deviation</p>
                  <p className="text-xl font-bold mt-0.5">{getSD(reportLot.id)} <span className="text-xs text-textSecondary">fps</span></p>
                </div>
                <div className="bg-[#1C1C1E] px-4 py-3">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Ext Spread</p>
                  <p className="text-xl font-bold mt-0.5">{getES(reportLot.id)} <span className="text-xs text-textSecondary">fps</span></p>
                </div>
                <div className="bg-[#1C1C1E] px-4 py-3">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Shots Logged</p>
                  <p className="text-xl font-bold mt-0.5">{getShotCountForLot(reportLot.id)}</p>
                </div>
                <div className="bg-[#1C1C1E] px-4 py-3">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Avg Vertical</p>
                  <p className="text-xl font-bold mt-0.5">{getAvgVertical(reportLot.id)} <span className="text-xs text-textSecondary">in</span></p>
                </div>
              </div>

              {/* Cost Section */}
              <div className="border-t border-[#2C2C2E] px-4 py-3 flex justify-between items-center">
                <div>
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Investment</p>
                  <p className="text-lg font-bold">${getLotCost(reportLot).toFixed(2)}</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Cost/Round</p>
                  <p className="text-lg font-bold">${getLotCostPerRound(reportLot).toFixed(3)}</p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] text-textSecondary uppercase tracking-wider">Remaining</p>
                  <p className="text-lg font-bold">{reportLot.quantityRemaining.toLocaleString()}</p>
                </div>
              </div>

              {/* Footer */}
              <div className="border-t border-[#2C2C2E] px-4 py-2.5 flex justify-between items-center">
                <p className="text-[10px] text-textSecondary">
                  Generated {new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                </p>
                <p className="text-[10px] text-textSecondary font-semibold bg-gradient-to-r from-green-400 to-emerald-500 bg-clip-text text-transparent">
                  Level<span className="font-black">UP</span> Precision
                </p>
              </div>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3 mt-4">
              <button
                onClick={() => setReportLotId(null)}
                className="flex-1 flex items-center justify-center gap-2 bg-[#2C2C2E] rounded-xl py-3 active:scale-95 transition-transform"
              >
                <X className="w-4 h-4" />
                <span className="text-sm font-semibold">Close</span>
              </button>
              <button
                onClick={handleShare}
                className="flex-1 flex items-center justify-center gap-2 bg-gradient-to-r from-green-400 to-emerald-500 text-black rounded-xl py-3 active:scale-95 transition-transform font-bold"
              >
                <Share2 className="w-4 h-4" />
                <span className="text-sm">Share</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
